version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nostos
      POSTGRES_USER: nostos
      POSTGRES_PASSWORD: nostos_local
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U nostos']
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    networks:
      - nostos-network

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - nostos-network
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minio_user minio_password;
      /usr/bin/mc mb myminio/nostos-uploads;
      /usr/bin/mc policy set public myminio/nostos-uploads;
      exit 0;
      "

networks:
  nostos-network:

volumes:
  postgres_data:
  minio_data:
